---
swagger: "2.0"
info:
  description: "<p>To consume our RESTful APIs, you need to have a Benchmark Email\
    \ API token. You can get your API key by going to https://ui.benchmarkemail.com/Integrate#API</p>\
    \    <p>Our APIs give you a limit of 500 calls per 2 minutes and 60,000 calls\
    \ total per day.</p>  "
  version: "1.0"
  title: "Benchmark Email API - Public"
host: "virtserver.swaggerhub.com"
basePath: "/tradingbills/benchmark-email_api_public/1.0"
schemes:
- "https"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /Engagement/CampaignList:
    get:
      tags:
      - "Engagement"
      summary: "Get a Campaign List of Engagement"
      description: "<h4>Get a Campaign List of Engagement</h4>\n<b>Query string parameters\
        \ :</b>\n<table>\n  <thead>\n    <tr>\n      <th>Parameter</th>\n      <th>Required</th>\n\
        \      <th>Type</th>\n      <th>Description</th>\n    </tr>\n  </thead>\n\
        \  <tbody>\n    <tr>\n      <td>PageNumber</td>\n      <td>Optional</td>\n\
        \      <td>string</td>\n      <td>Page Number</td>\n    </tr>\n    <tr>\n\
        \      <td>PageSize</td>\n      <td>Optional</td>\n      <td>string</td>\n\
        \      <td>Number of rows on the page</td>\n    </tr>\n    <tr>\n      <td>OrderBy</td>\n\
        \      <td>Optional</td>\n      <td>string</td>\n      <td>Order By Column</td>\n\
        \    </tr>\n    <tr>\n      <td>Filter</td>\n      <td>Optional</td>\n   \
        \   <td>string</td>\n      <td>Filter by name</td>\n    </tr>\n    <tr>\n\
        \      <td>SortOrder</td>\n      <td>Optional</td>\n      <td>string</td>\n\
        \      <td>ASC or DESC</td>\n    </tr>\n  </tbody>\n</table>\n\n<b>Response\
        \ body parameters :</b>\n<table>\n  <thead>\n    <tr>\n      <th>Parameter</th>\n\
        \      <th>Type</th>\n      <th>Description</th>\n    </tr>\n  </thead>\n\
        \  <tbody>\n    <tr>\n      <td>Count</td>\n      <td>int</td>\n      <td>Total\
        \ number</td>\n    </tr>\n    <tr>\n      <td>Status</td>\n      <td>string</td>\n\
        \      <td>1 = Successful, -1 Error</td>\n    </tr>\n    <tr>\n      <td>Data</td>\n\
        \      <td><a href=\"http://www.benchmarkemail.com/models.htm#EngagementCampaignData\"\
        \ > CampaignData</a></td>\n      <td>Array of Campaign list returned.</td>\n\
        \    </tr>\n  </tbody>\n</table>"
      operationId: "EngagementCampaignListGet"
      produces:
      - "application/json"
      parameters:
      - name: "PageNumber"
        in: "query"
        description: ""
        required: true
        type: "string"
      - name: "PageSize"
        in: "query"
        description: ""
        required: true
        type: "string"
      - name: "OrderBy"
        in: "query"
        description: ""
        required: true
        type: "string"
      - name: "Filter"
        in: "query"
        description: ""
        required: true
        type: "string"
      - name: "SortOrder"
        in: "query"
        description: ""
        required: true
        type: "string"
      - name: "AuthToken"
        in: "header"
        description: ""
        required: true
        type: "string"
      - name: "Content-Type"
        in: "header"
        description: ""
        required: true
        type: "string"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/GetACampaignListOfEngagement"
          examples:
            application/json:
              Response:
                Count: 51
                Data:
                - Clicks: 0
                  EmailName: "Test Pooja"
                  ID: "12263198"
                  MailSent: 8
                  Opens: 0
                  ScheduleDate: "Oct 06, 2017"
                  TimeZone: "IST"
                - Clicks: 0
                  EmailName: "Aug 21 2017 Email 1"
                  ID: "12194338"
                  MailSent: 5
                  Opens: 0
                  ScheduleDate: "Aug 24, 2017"
                  TimeZone: "IST"
                - Clicks: 0
                  EmailName: "Aug 24 2017 Email"
                  ID: "12211505"
                  MailSent: 11
                  Opens: 0
                  ScheduleDate: "Aug 24, 2017"
                  TimeZone: "IST"
                - Clicks: 0
                  EmailName: "ISSUE Campaign Copy Copy Copy"
                  ID: "12210851"
                  MailSent: 3998
                  Opens: 0
                  ScheduleDate: "Aug 24, 2017"
                  TimeZone: "IST"
                - Clicks: 0
                  EmailName: "ISSUE Campaign Copy Copy"
                  ID: "12210437"
                  MailSent: 3998
                  Opens: 0
                  ScheduleDate: "Aug 24, 2017"
                  TimeZone: "IST"
                Status: "1"
      security: []
      x-unitTests:
      - request:
          method: "GET"
          uri: "/Engagement/CampaignList?PageNumber={{PageNumber}}&PageSize={{PageSize}}&OrderBy={{OrderBy}}&Filter={{Filter}}&SortOrder={{SortOrder}}"
          headers:
            AuthToken: "{{Authentication Token}}"
            Content-Type: "application/json"
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: "RAW"
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers:
            access-control-allow-origin: "*"
            cache-control: "private"
            content-type: "application/json; charset=utf-8"
            date: "Mon, 23 Oct 2017 05:38:33 GMT"
            server: "Microsoft-IIS/8.0"
            transfer-encoding: "chunked"
            x-aspnet-version: "4.0.30319"
            x-powered-by: "ASP.NET"
          body: "{\"Response\":{\"Count\":51,\"Data\":[{\"Clicks\":0,\"EmailName\"\
            :\"Test Pooja\",\"ID\":\"12263198\",\"MailSent\":8,\"Opens\":0,\"ScheduleDate\"\
            :\"Oct 06, 2017\",\"TimeZone\":\"IST\"},{\"Clicks\":0,\"EmailName\":\"\
            Aug 21 2017 Email 1\",\"ID\":\"12194338\",\"MailSent\":5,\"Opens\":0,\"\
            ScheduleDate\":\"Aug 24, 2017\",\"TimeZone\":\"IST\"},{\"Clicks\":0,\"\
            EmailName\":\"Aug 24 2017 Email\",\"ID\":\"12211505\",\"MailSent\":11,\"\
            Opens\":0,\"ScheduleDate\":\"Aug 24, 2017\",\"TimeZone\":\"IST\"},{\"\
            Clicks\":0,\"EmailName\":\"ISSUE Campaign Copy Copy Copy\",\"ID\":\"12210851\"\
            ,\"MailSent\":3998,\"Opens\":0,\"ScheduleDate\":\"Aug 24, 2017\",\"TimeZone\"\
            :\"IST\"},{\"Clicks\":0,\"EmailName\":\"ISSUE Campaign Copy Copy\",\"\
            ID\":\"12210437\",\"MailSent\":3998,\"Opens\":0,\"ScheduleDate\":\"Aug\
            \ 24, 2017\",\"TimeZone\":\"IST\"}],\"Status\":\"1\"}}"
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: "Get a Campaign List of Engagement"
        x-testDescription: "<h4>Get a Campaign List of Engagement</h4>\n<b>Query string\
          \ parameters :</b>\n<table>\n  <thead>\n    <tr>\n      <th>Parameter</th>\n\
          \      <th>Required</th>\n      <th>Type</th>\n      <th>Description</th>\n\
          \    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td>PageNumber</td>\n\
          \      <td>Optional</td>\n      <td>string</td>\n      <td>Page Number</td>\n\
          \    </tr>\n    <tr>\n      <td>PageSize</td>\n      <td>Optional</td>\n\
          \      <td>string</td>\n      <td>Number of rows on the page</td>\n    </tr>\n\
          \    <tr>\n      <td>OrderBy</td>\n      <td>Optional</td>\n      <td>string</td>\n\
          \      <td>Order By Column</td>\n    </tr>\n    <tr>\n      <td>Filter</td>\n\
          \      <td>Optional</td>\n      <td>string</td>\n      <td>Filter by name</td>\n\
          \    </tr>\n    <tr>\n      <td>SortOrder</td>\n      <td>Optional</td>\n\
          \      <td>string</td>\n      <td>ASC or DESC</td>\n    </tr>\n  </tbody>\n\
          </table>\n\n<b>Response body parameters :</b>\n<table>\n  <thead>\n    <tr>\n\
          \      <th>Parameter</th>\n      <th>Type</th>\n      <th>Description</th>\n\
          \    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td>Count</td>\n    \
          \  <td>int</td>\n      <td>Total number</td>\n    </tr>\n    <tr>\n    \
          \  <td>Status</td>\n      <td>string</td>\n      <td>1 = Successful, -1\
          \ Error</td>\n    </tr>\n    <tr>\n      <td>Data</td>\n      <td><a href=\"\
          http://www.benchmarkemail.com/models.htm#EngagementCampaignData\" > CampaignData</a></td>\n\
          \      <td>Array of Campaign list returned.</td>\n    </tr>\n  </tbody>\n\
          </table>"
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      x-swagger-router-controller: "Engagement"
definitions:
  GetACampaignListOfEngagement:
    type: "object"
    required:
    - "Response"
    properties:
      Response:
        $ref: "#/definitions/GetACampaignListOfEngagement_Response"
    title: "Get a Campaign List of Engagement"
    example:
      Response:
        Count: 51
        Data:
        - Clicks: 0
          EmailName: "Test Pooja"
          ID: "12263198"
          MailSent: 8
          Opens: 0
          ScheduleDate: "Oct 06, 2017"
          TimeZone: "IST"
        - Clicks: 0
          EmailName: "Aug 21 2017 Email 1"
          ID: "12194338"
          MailSent: 5
          Opens: 0
          ScheduleDate: "Aug 24, 2017"
          TimeZone: "IST"
        - Clicks: 0
          EmailName: "Aug 24 2017 Email"
          ID: "12211505"
          MailSent: 11
          Opens: 0
          ScheduleDate: "Aug 24, 2017"
          TimeZone: "IST"
        - Clicks: 0
          EmailName: "ISSUE Campaign Copy Copy Copy"
          ID: "12210851"
          MailSent: 3998
          Opens: 0
          ScheduleDate: "Aug 24, 2017"
          TimeZone: "IST"
        - Clicks: 0
          EmailName: "ISSUE Campaign Copy Copy"
          ID: "12210437"
          MailSent: 3998
          Opens: 0
          ScheduleDate: "Aug 24, 2017"
          TimeZone: "IST"
        Status: "1"
  GetACampaignListOfEngagement_Response:
    required:
    - "Count"
    - "Data"
    - "Status"
    properties:
      Count:
        type: "integer"
        format: "int32"
        example: 51
        description: ""
      Data:
        type: "array"
        example:
        - Clicks: 0
          EmailName: "Test Pooja"
          ID: "12263198"
          MailSent: 8
          Opens: 0
          ScheduleDate: "Oct 06, 2017"
          TimeZone: "IST"
        - Clicks: 0
          EmailName: "Aug 21 2017 Email 1"
          ID: "12194338"
          MailSent: 5
          Opens: 0
          ScheduleDate: "Aug 24, 2017"
          TimeZone: "IST"
        - Clicks: 0
          EmailName: "Aug 24 2017 Email"
          ID: "12211505"
          MailSent: 11
          Opens: 0
          ScheduleDate: "Aug 24, 2017"
          TimeZone: "IST"
        - Clicks: 0
          EmailName: "ISSUE Campaign Copy Copy Copy"
          ID: "12210851"
          MailSent: 3998
          Opens: 0
          ScheduleDate: "Aug 24, 2017"
          TimeZone: "IST"
        - Clicks: 0
          EmailName: "ISSUE Campaign Copy Copy"
          ID: "12210437"
          MailSent: 3998
          Opens: 0
          ScheduleDate: "Aug 24, 2017"
          TimeZone: "IST"
        description: ""
        items:
          $ref: "#/definitions/Data629"
      Status:
        type: "string"
        example: "1"
        description: ""
    example: "{\"Count\":51,\"Data\":[{\"Clicks\":0,\"EmailName\":\"Test Pooja\",\"\
      ID\":\"12263198\",\"MailSent\":8,\"Opens\":0,\"ScheduleDate\":\"Oct 06, 2017\"\
      ,\"TimeZone\":\"IST\"},{\"Clicks\":0,\"EmailName\":\"Aug 21 2017 Email 1\",\"\
      ID\":\"12194338\",\"MailSent\":5,\"Opens\":0,\"ScheduleDate\":\"Aug 24, 2017\"\
      ,\"TimeZone\":\"IST\"},{\"Clicks\":0,\"EmailName\":\"Aug 24 2017 Email\",\"\
      ID\":\"12211505\",\"MailSent\":11,\"Opens\":0,\"ScheduleDate\":\"Aug 24, 2017\"\
      ,\"TimeZone\":\"IST\"},{\"Clicks\":0,\"EmailName\":\"ISSUE Campaign Copy Copy\
      \ Copy\",\"ID\":\"12210851\",\"MailSent\":3998,\"Opens\":0,\"ScheduleDate\"\
      :\"Aug 24, 2017\",\"TimeZone\":\"IST\"},{\"Clicks\":0,\"EmailName\":\"ISSUE\
      \ Campaign Copy Copy\",\"ID\":\"12210437\",\"MailSent\":3998,\"Opens\":0,\"\
      ScheduleDate\":\"Aug 24, 2017\",\"TimeZone\":\"IST\"}],\"Status\":\"1\"}"
