---
swagger: "2.0"
info:
  description: "<p>To consume our RESTful APIs, you need to have a Benchmark Email\
    \ API token. You can get your API key by going to https://ui.benchmarkemail.com/Integrate#API</p>\
    \    <p>Our APIs give you a limit of 500 calls per 2 minutes and 60,000 calls\
    \ total per day.</p>  "
  version: "1.0"
  title: "Benchmark Email API - Public"
host: "virtserver.swaggerhub.com"
basePath: "/tradingbills/benchmark-email_api_public/1.0"
schemes:
- "https"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /Contact/ExportToList:
    get:
      tags:
      - "General"
      summary: "Get Export List"
      description: "Export List\r\n\r\n<h4>Query String Parameters</h4>\r\n<table>\r\
        \n<thead>\r\n<tr>\r\n<th>Key</th>\r\n<th>Required</th>\r\n<th>Description</th>\r\
        \n</tr>\r\n</thead>\r\n<tbody>\r\n<tr>\r\n<td>ReportFor</td>\r\n<td>optional</td>\r\
        \n<td><ul><li><code>1</code> - Clicks</li><li><code>2</code> - Forwards</li><li><code>3</code>\
        \ - Bounces</li><li><code>5</code> - Unsubscribe</li><li><code>6</code> -\
        \ Opens</li><li><code>7</code> - Unopens</li><li><code>8</code> – Clicks For\
        \ url</li><li><code>11</code> - Individual Survey</li><li><code>12</code>\
        \ - Opens State Wise</li></ul></td>\r\n</tr>\r\n<tr><td>EmailID</td><td>optional</td><td>Unique\
        \ ID (i.e Campaign ID)</td></tr>\r\n<tr>\r\n<td>IsOverWrite</td>\r\n<td>optional</td>\r\
        \n<td><ul><li><code>1</code> - OverWrite if List Exists</li><li><code>0</code>\
        \ - Don't Over Write if List Exists (It will stop process if list found with\
        \ the same name)</li></td>\r\n</tr>\r\n</ul>\r\n<tr><td>LinkName</td><td>optional</td><td>Name\
        \ of link</td></tr>\r\n<tr>\r\n<td>Filter</td>\r\n<td>optional</td>\r\n<td><ul><li><code>1</code>\
        \ - Soft Bounces</li><li><code>2</code> - Hard Bounces</li></ul></td>\r\n\
        </tr>\r\n<tr><td>Region</td><td>optional</td><td>Region or  State</td></tr>\r\
        \n\r\n</tbody>\r\n</table>\r\n\r\n<h4>Response body parameters</h4>\r\n<table>\r\
        \n<thead>\r\n<tr>\r\n<th>Key</th><th>Type</th><th>Description</th></tr>\r\n\
        </thead>\r\n<tbody>\r\n<tr><td>Status</td><td>string</td><td>1 if successful,\
        \ -1 if error</td></tr>\r\n<tr><td>ReportTypeText</td><td>string</td><td>Returns\
        \ the report type like bounces,SURVEY RESPONDENTS,OPENS etc</td></tr>\r\n\
        <tr><td>ListName</td><td>string</td><td>List Name</td></tr>\r\n</tbody>\r\n\
        </table>"
      operationId: "ContactExportToListGet"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "AuthToken"
        in: "header"
        description: ""
        required: true
        type: "string"
      - name: "Content-Type"
        in: "header"
        description: ""
        required: true
        type: "string"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/GetExportList"
          examples:
            application/json:
              Response:
                ListName: "Unopened Report : Oct 06 2017 Email 1"
                ReportTypeText: "UNOPENS"
                Status: "1"
      security: []
      x-unitTests:
      - request:
          method: "GET"
          uri: "/Contact/ExportToList"
          headers:
            AuthToken: "{{Authentication Token}}"
            Content-Type: "application/json"
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: "RAW"
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers:
            access-control-allow-origin: "*"
            cache-control: "private"
            content-type: "application/json; charset=utf-8"
            date: "Tue, 17 Oct 2017 05:51:36 GMT"
            server: "Microsoft-IIS/8.0"
            transfer-encoding: "chunked"
            x-aspnet-version: "4.0.30319"
            x-powered-by: "ASP.NET"
          body: "{\"Response\":{\"ListName\":\"Unopened Report : Oct 06 2017 Email\
            \ 1\",\"ReportTypeText\":\"UNOPENS\",\"Status\":\"1\"}}"
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: "Get Export List"
        x-testDescription: "Export List    Query String Parameters        Key  Required\
          \  Description          ReportFor  optional  <ul><li><code>1</code> - Clicks</li><li><code>2</code>\
          \ - Forwards</li><li><code>3</code> - Bounces</li><li><code>5</code> - Unsubscribe</li><li><code>6</code>\
          \ - Opens</li><li><code>7</code> - Unopens</li><li><code>8</code> – Clicks\
          \ For url</li><li><code>11</code> - Individual Survey</li><li><code>12</code>\
          \ - Opens State Wise</li></ul>    EmailIDoptionalUnique ID (i.e Campaign\
          \ ID)    IsOverWrite  optional  <ul><li><code>1</code> - OverWrite if List\
          \ Exists</li><li><code>0</code> - Don't Over Write if List Exists (It will\
          \ stop process if list found with the same name)</li>    </ul>  LinkNameoptionalName\
          \ of link    Filter  optional  <ul><li><code>1</code> - Soft Bounces</li><li><code>2</code>\
          \ - Hard Bounces</li></ul>    RegionoptionalRegion or  State          Response\
          \ body parameters        KeyTypeDescription      Statusstring1 if successful,\
          \ -1 if error  ReportTypeTextstringReturns the report type like bounces,SURVEY\
          \ RESPONDENTS,OPENS etc  ListNamestringList Name    "
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      x-swagger-router-controller: "General"
definitions:
  GetExportList:
    type: "object"
    required:
    - "Response"
    properties:
      Response:
        $ref: "#/definitions/Response126"
    title: "Get Export List"
    example:
      Response:
        ListName: "Unopened Report : Oct 06 2017 Email 1"
        ReportTypeText: "UNOPENS"
        Status: "1"
  Response126:
    type: "object"
    required:
    - "ListName"
    - "ReportTypeText"
    - "Status"
    properties:
      ListName:
        type: "string"
        example: "Unopened Report : Oct 06 2017 Email 1"
        description: ""
      ReportTypeText:
        type: "string"
        example: "UNOPENS"
        description: ""
      Status:
        type: "string"
        example: "1"
        description: ""
    title: "Response126"
    example:
      ListName: "Unopened Report : Oct 06 2017 Email 1"
      ReportTypeText: "UNOPENS"
      Status: "1"
